name: Stradal Contact Build
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'docs/**/*'
    branches: 
      - main
      - release-*
    tags:
      - 'v*'
  pull_request:
    branches: 
      - master
      - release-*
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Build, Test, Publish
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0
    - name: Initialize HexalithApp submodule
      run: |
          git submodule init HexalithApp
          git submodule update HexalithApp
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Aspire Workloads
      run: |
        dotnet workload install aspire
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 5.0.0
        version=$(minver -t v -v e -d preview)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "VERSION=$version"
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/Contacts.UnitTests/Contacts.UnitTests.csproj
    - name: Check the container registry parameters
      run: |
        echo "Registry: ${{ vars.AZURE_REGISTRY }}"
        echo "User Name: ${{ secrets.AZURE_APPLICATIONID }}"
        echo "Password: ${{ secrets.AZURE_APPLICATIONSECRET }}"
    - name: Login to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_APPLICATIONID }}
        password: ${{ secrets.AZURE_APPLICATIONSECRET }}
    - name: Publish and push the Contact Web server container images to the container registry
      run: |
          dotnet publish './HexalithApp/src/HexalithApp.Server/HexalithApp.Server.csproj' /t:PublishContainer --configuration Release --os linux --arch x64 -p:ContainerImageTags='"${{ env.VERSION }};latest"' -p:ContainerRegistry=${{ vars.AZURE_REGISTRY }} -p:ContainerRepository='contact'
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_APPLICATIONID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID  }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
    - name: Deploy to Azure Container Apps
      run: az account show
    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name int-contact \
          --resource-group hex-integration \
          --image ${{ vars.AZURE_REGISTRY }}/contact:${{ env.VERSION }}
 
